name: Build and Release Start9 Package

on:
  push:
    tags:
      - "v*"

jobs:
  BuildPackage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the service package
        id: build
        shell: bash
        run: |
          git submodule update --init --recursive || true
          start-sdk init
          make
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          printf "\nSHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk)\n"

      - name: Upload .s9pk artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package_id }}.s9pk
          path: ./${{ env.package_id }}.s9pk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./${{ env.package_id }}.s9pk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
